### PR TITLE
Adding a style guide page

### PR DESCRIPTION
**Pull request by martin-nc**
I've created a style guide page. Please feel free to suggest amendments. One outstanding issue is whether we treat 'data' as a singular or plural ("Data is..." or "Data are..."). I think this [Guardian article](https://www.theguardian.com/news/datablog/2010/jul/16/data-plural-singular) and the [Wikipedia page](https://en.wikipedia.org/wiki/Data_(word)) summarise the situation well. The modern tendency is to treat 'data' as an uncountable noun, and so say "Data is...". In my experience of everyday use this is definitely right - 'Data are..." sounds archaic. But there are some areas of academia where the word is still treated as plural. Is data management one of them? (That wasn't a rhetorical question - I don't know the answer!)

**Edit:** forgot to add the preview: https://martin-nc.github.io/martinc-rdm-toolkit/style_guide.html

### CODE REVIEW

**Comment by bedroesb** [comment]
@martin-nc I was wondering if the colors in the rdm wheel could be reused in those corresponding pages?

**Comment by martin-nc** [comment]
@bedroesb Yes, I think that was the original plan. I'd forgotten. I've updated the text.

**Comment by bedroesb** [comment]
Do we also make it visible in the side panel?

Something like: 

```
entries:
    - title: Contribute
      folders:
      - title: How to contribute
        url: /how_to_contribute.html
      - title: Github way
        url: /github_way.html
      - title: Google doc way
        url: /google_doc_way.html
      - title: Style guide
        url: /style_guide.html
      - title: Demo page
        url: /demo_page.html
```

in contribute.yml in the _data directory

**Comment by martin-nc** [comment]
@bedroesb Yes, I was going to do that in a separate pull request, when everyone was happy with the style guide. I've bundled that change in now, though.

**Review by bedroesb — APPROVED** [review]

**Comment by bedroesb** [comment]
Sorry, didn't want to be pushy. I personally am already very happy with having this style guide before the contentathon :)

**Comment by martin-nc** [comment]
No problem. In retrospect, it makes more sense to push the changes through together.

**Review by pinarpink — APPROVED** [review]
Martin, my apologies in reviewing the style guide. Thank you for providing a preview page, it saved time. It looks very good to me. Many thanks!

**Pull request merged**
