### PR TITLE
Toollist search/sort/paging

### PR DESCRIPTION
**Pull request by bedroesb**
Added searching, sorting and paging to the tool list:

image

### CODE REVIEW

**Comment by martin-nc** [comment]
Are the arrows on the tool names necessary? Maybe it's cleaner without them?

**Comment by bedroesb** [comment]
done + overflow with mobile:

image

**Comment by bedroesb** [comment]
ok that became a huge screenshot... :)

**Comment by martin-nc** [comment]
Looks better to me! 

Would it be useful to make the tags links? Or would that just be too many links on the page?

**Comment by bedroesb** [comment]
I like the idea, but maybe we can open a separate issue about that?

**Pull request merged**
