### PR TITLE
Home page spacing tweaks

### PR DESCRIPTION
**Pull request by martin-nc**
1. Added spacing around the notice box at the top.
2. Removed top margin of the footer (too much space because the RDM diagram already has a large bottom margin set).
3. Created a variable in the home page front matter called `style`, set to 'home'. I used this to target the home page footer only:
`<footer id="footer" class="site-footer {% if page.style %}{{ page.style }} {% endif %}">`

CSS:
```
.home.site-footer {
  margin-top: 0;
}
```
But it might be handy to give custom styles to other elements on the home page. @bedroesb  is that okay? Maybe there was a simpler way.

Preview of changes here: https://martin-nc.github.io/martinc-rdm-toolkit/

### CODE REVIEW

**Comment by martin-nc** [comment]
Pushed from the wrong repo and has unwanted commits in.

**Comment by bedroesb** [comment]
@martin-nc If you want to achieve the same without additional frontmatter, you could change your Jekyll to  <footer id="footer" class="site-footer {% if page.url == index.html %}{{ home }} {% endif %}">.

**Comment by martin-nc** [comment]
@bedroesb looks like a bit of your comment got removed. What was the Jekyll? I'll create a new pull request with the new code in.

**Comment by bedroesb** [comment]
sorry about that, fixed!

**Comment by martin-nc** [comment]
@bedroesb That's interesting - it doesn't work for me. I tried all the options in [this thread](https://stackoverflow.com/questions/28932707/check-if-current-page-is-homepage-on-jekyll) and they didn't work, either. Only the front matter approach worked.

**Comment by bedroesb** [comment]
I am sorry, it is not url, but permalink, I use it for the coloring of the lifecycle wheel: 
```
{%- capture re-using -%}{%- if page.permalink == "re-using.html" -%}st0{%- else -%}st10{%- endif -%}{%- endcapture -%}
```

**Comment by bedroesb** [comment]
just figured out that this logic is deprecated in the latest version of the website due to my permalink changes in #104 .

**Comment by martin-nc** [comment]
Maybe having a `style` variable in the front matter isn't a bad idea. I think the original idea above is poor because it just checks for the presence of the variable. It could check for the value instead `{% if page.style == 'home' %}{{page.style}}{% endif %} `. That means we have an option of styling different elements of the site differently according the page you're on. It does it in a way that's simpler than checking the permalink because the snippet doesn't need to change each page (because you have to put different permalinks in). Anyway, just a thought - not urgent or perhaps necessary for now.

**Comment by bedroesb** [comment]
If we want to do that in the future I agree having a style variable in the attributes is the easiest way to do so.

Small thing i just noticed we might wonna apply your margin changes to all message boxes:

Screenshot from 2020-10-13 15-07-37

**Pull request closed without merging**
