### PR TITLE
Improved tool + resource table + CONTRIBUTING + css/icon improvements

### LINKED ISSUE #52: Linking the tags in the toollist to pages
A proposal by @martin-nc in PR #51 , we could make the tags in the toollist clickable. But than we should decide on the tags and to which page they refer to.

### LINKED ISSUE #75: Merge tools and resources tables
@bedroesb The editorial board decided to DO NOT separate tools and resources. We would like to have only ONE table with "tools and resources" together.

### PR DESCRIPTION
**Pull request by bedroesb**
- [x] one excel/yaml list for both tools and resources
- [x] one yaml file listing all allowed tags (for pages, tools and resources,...) 
- [x] linking pages through tags
- [x] coloring the tags (took the same colors as in the RDM cycle wheel
- [x] registry column to link towards bio.tools and FAIRsharing
- [x] updating demo page/documentation in usage
- [x] moving how_to_contribute to CONTRIBUTING in root 
- [x] allowing both fairsharing and Bio.tools
- [x] replace all png icons to svg
- [x] better icons for fairsharing and Bio.tools
- [x] table of content css improvements #49 

image

Preview can be seen here:
https://bedroesb.github.io/rdm-toolkit/all_tools_and_resources.html

close #75 and close #52

### CODE REVIEW

**Comment by martin-nc** [comment]
Is it worth swapping the positions of the 'Show [number] entries' field and the Search box? Or even putting them together to the left so you get 'Search' then the 'Show entries' field just after? I just thought the search might be more useful.

**Comment by bedroesb** [comment]
@martin-nc sadly this is not easy to snap due to the used javascript library of bootstrap/jquery. I could change it, but than I lose the possibility to go to newer versions easily.

**Comment by martin-nc** [comment]
@bedroesb Ah, okay. Just on the 'Do we need to make a visual distinction between tools and resources?' question, I think we talked about this briefly last Friday, and decided it's probably difficult to distinguish between a 'tool' and a 'resource' so it's best not to distinguish them. Maybe I've misremembered, though. You could spend quite a bit of time wringing your hands over the definitions of 'tool' and 'resource'!

**Comment by bedroesb** [comment]
@martin-nc thank you for the update! at this moment I was making a distinction on the yaml too, because I need to know whether the registry ID is for bio.tools or for FAIRsharing.... than I should save the full links towards these registries

**Comment by martin-nc** [comment]
@bedroesb I think the idea was to keep the header vague i.e. 'Tools and resources', but I think it's best to check with the others.

**Comment by nsoranzo** [comment]
> I think we talked about this briefly last Friday, and decided it's probably difficult to distinguish between a 'tool' and a 'resource' so it's best not to distinguish them. Maybe I've misremembered, though. You could spend quite a bit of time wringing your hands over the definitions of 'tool' and 'resource'!

Agreed, it can be challenging to distinguish among "tool", "resource", and also "service".

> I need to know whether the registry ID is for bio.tools or for FAIRsharing

In fact, there may be a resource that has both a bio.tools and FAIRsharing ID, and we may want to add more registries in the future (like standards, there are never enough registries :).

**Comment by bedroesb** [comment]
ok maybe I can list the registries as icons in the registry column and allow multiple values in the registry field in the yaml file/excel file

**Comment by bedroesb** [comment]
image

Support for multiple registries and new icons

**Pull request merged**
