### PR TITLE
Contributor carousel on landing page

### PR DESCRIPTION
**Pull request by bedroesb**
The contributors are determined based on the contributor list in the metadata on page level + the CONTRIBUTORS yaml file. In this case people that are contributing but not on page level are mentioned + people that do not have a github will also be mentioned. If available, the email, orcid and github account is linked

Screenshot from 2021-01-19 22-25-54

This update also contains following dependency updates:
- bootstrap v3.3.6
- jquery v2.2.4
- AnchorJS - v4.3.0
- fontawesome 5 
- latest toc.js
- simple-jeckyll-search v1.9.1 

Also new is:
- anchor for h2 titles is now on the left + better
- no icon placement for external links
- no home style
- javascript cleanup
- adds the editors to the about page

you can preview it [here](https://bedroesb.github.io/rdm-toolkit/)

### CODE REVIEW

**Comment by floradanna** [comment]
I suggest to make the carousel smaller, or to make the contributors' section smaller.
I would maybe put the carousel in the About page, instead of in the landing page.

**Comment by bedroesb** [comment]
@floradanna I would keep it on the landing page, nobody visits the about and it is something people can be proud of no? :)

**Comment by floradanna** [comment]
@bedroesb yes, but users come to read guidelines about RDM, not to see who wrote the guidelines (it's also clear that ELIXIR wrote them). If users want to know us, they click on About. This is just my opinion :)

**Comment by bedroesb** [comment]
@bedroesb lets see what the other think of it in the editorial meeting :)

**Pull request merged**
