### PR TITLE
Update Your domain - Human data

### PR DESCRIPTION
**Pull request by nicjar**
Issue #280 

Content edited and expanded for these sections:
* Taking ethical and legal implications into consideration for Planning and Collection
* Processing and Analysing human data

### CODE REVIEW

**Review by pinarpink — APPROVED** [review]
Thanks @nicjar. This would be our baseline for the gap analysis we will do in Jan 2021 contentathon.

**Review by floradanna — CHANGES_REQUESTED** [review]
Thanks for this contribution. Please, make sure that all tools and resources mentioned are added to the tool and resource table as described in the [guide](https://rdm.elixir-europe.org/tool_resource_update.html#making-changes).

**Comment by nicjar** [comment]
> Thanks for this contribution. Please, make sure that all tools and resources mentioned are added to the tool and resource table as described in the [guide](https://rdm.elixir-europe.org/tool_resource_update.html#making-changes).

Resources added to tools and resources list.

**Comment by bedroesb** [comment]
@nicjar your edit in the tooltable brings in a sentence with commas, in this case you have to put it within quotes `"text"`

**Comment by nicjar** [comment]
@bedroesb yes, I noticed, thanks! Working on it. Will monitor the checks until it passes

**Review by floradanna — APPROVED** [review]

**Pull request merged**
