### PR TITLE
Update data_life_cycle.md

### PR DESCRIPTION
**Pull request by OlivierCollin**
Tentative list.

### CODE REVIEW

**Comment by martin-nc** [comment]
Could we change 'Share and publish' to just 'Share'? Then it would be one word like the rest, and be consistent with other RDM diagrams e.g. https://www.fws.gov/data/life-cycle.

**Comment by OlivierCollin** [comment]
Yes, that makes sense for me. 
Does any scientific information specialist has any ideas about this ?

**Comment by korbinib** [comment]
I feel that there is strong feelings connected to the titles of the life cycle stages.
The most wide spread seem to be:
- Re-using data
- Creating data
- Processing data
- Analysing data
- Preserving data
- Giving access to data

The DSW uses some slightly different terms:
- Re-using data
- Creating and collecting data
- Processing data
- Interpreting data
- Preserving data
- Giving access to data

**Comment by bedroesb** [comment]
We went for a diagram on the landing page to refer to the life cycle. Thank you for starting this topic in this PR.

**Pull request closed without merging**
