### PR TITLE
Add a 'Why is Data Collection important?' section

### PR DESCRIPTION
**Pull request by YvonneKallberg**
Issue #285
Suggestion of text to the mentioned section, as well as removing a dot in the list of considerations and adding a hyphen to Re-use (since this is how it is spelled in the side menu of the toolkit).

### CODE REVIEW

**Review by floradanna — APPROVED** [review]
Thank you for adding the missing paragraph.

**Review by smza — COMMENTED** [review]
Thanks Yvonne. We just need to change the Re-use back  to Reuse, as this is what we decided in the recent meeting.

**Comment by bedroesb** [comment]
good catch @smza , do i quickly fix it?

**Comment by smza** [comment]
> good catch @smza , do i quickly fix it?

yes please! Thanks Bert!

**Pull request merged**
