### PR TITLE
Update data_organisation.md

### PR DESCRIPTION
**Pull request by YvonneKallberg**
Issue #292 
Add text to file versioning and folder structure sections.

### CODE REVIEW

**Review by floradanna — CHANGES_REQUESTED** [review]
Thanks for this content!
Have you added the tools you mentioned here in the "tools and resources" table (as described[ here](https://rdm.elixir-europe.org/tool_resource_update.html#making-changes))?
If GitHub, BitBucket etc... are already in the table, you don't need to add them again. If not, please add them.

**Comment by bedroesb** [comment]
The respective tag you want to use for the tools in this case is `data organisation`

**Comment by YvonneKallberg** [comment]
GitHub was already listed, I've added Bitbucket and Git. I saw that Minna & Siiri also mentioned a couple of tools for bulk renaming of files ([Bulk Rename Utility](https://www.bulkrenameutility.co.uk/), [Renamer4Mac](https://renamer.com/)), should they be added as well?

**Comment by floradanna** [comment]
Yes, please. Thanks Yvonne!

**Comment by YvonneKallberg** [comment]
Bulk renaming tools are now added to the tools and resources list

**Review by floradanna — APPROVED** [review]

**Pull request merged**
