### PR TITLE
Allow direct links to TeSS materials and events

### PR DESCRIPTION
**Pull request by christopherchild**
It was pointed out that it would be useful to be able to link directly to specific materials in TeSS.

I have updated the snippet/include (tess.html) to allow this:

Link to search query
`{% include tess.html search="Data Steward" %}`

Link to material
`{% include tess.html material="data-management-plans-why-and-how" %}`

Link to event
`{% include tess.html event="advanced-python-for-biologists-2020" %}`

Currently the text next to the TeSS logo is the same for all types of links. This might be better if there was a distinction between search, material and event. I'm happy to change this.

image

### CODE REVIEW

**Comment by bedroesb** [comment]
I don't see the purpose in specific links towards events or temporary things using this approach. People will have to remember to take this link out of the page again, and I am scared that that will not happen... I would keep this in mind if we have something automatic that checks every few days (using the tess API) for events or topics and we maybe list the options nicely instead of a generic button.
Also if they want to list multiple links, we will have to approach this differently I think ...

Maybe we can open an issue about listing training ?

**Review by bedroesb — APPROVED** [review]

**Comment by bedroesb** [comment]
This code snippet will be used for manual linking to course material and is seperate from the link between TeSS and the tool/resource table.

**Comment by bedroesb** [comment]
@christopherchild Do you think this is ready for merge?

**Comment by christopherchild** [comment]
Do you want me to remove the events are you happy to leave it in?

Other than that it is good to go.

**Comment by bedroesb** [comment]
I guess we can warn people if they link towards events that it is important to take the link away after the event has happen, which reminds me of something else. We should add a how to use this in the [markdown cheat sheet](https://github.com/elixir-europe/rdm-toolkit/blob/master/pages/contribute/markdown_cheat_sheet.md).

**Comment by christopherchild** [comment]
I'll get the cheat sheet updated and update this PR.

**Comment by DanFaria** [comment]
I don't think we're in the business of listing or linking to specific events.
We can list persistent things such as training programmes and such, but temporary things are outside the scope of the toolkit, in my opinion.
We don't want to redo TeSS or do a data managament flavored version of it.

**Comment by pinarpink** [comment]
@DanFaria  this was discussed in our WP2-WP3 link up meetings. And the intention is to link to training materials and learning paths not to events.

**Comment by bedroesb** [comment]
@christopherchild Do you allow me to make these changes on top of your pull request?  Updating the cheat sheet and taking away events. I was also maybe thinking of making the code snippet more distinguishable design wise from the one in the tool list added in #240

**Comment by bedroesb** [comment]
@christopherchild Thank you for updating the snippet. I included the snippets for the TeSS button in my latest PR #243. Is it OK for you to merge this PR ?

**Comment by bedroesb** [comment]
@christopherchild I think pulling from my feature branch will cause merge problems with #243 ?I meant merging this PR to the master, so I can adapt my changes to these :) Sorry for the confusion!

**Comment by christopherchild** [comment]
No problem, I will revert the merge. Do you want me to complete the PR?

**Comment by bedroesb** [comment]
I think if your changes to the tess snippet are in this PR and we merge them to the master

```
{%- if {{include.search}} %}
<a
  class="no_icon nohover"
  data-toggle="tooltip"
  title="TeSS Search: {{include.search}}"
  href="https://tess.elixir-europe.org/search?q={{include.search}}" >
  Topic related training:
  <img
    style="background-color: #f47d20"
    class="registry_logo"
    src="images/tess_logo.svg"
    alt="TeSS logo" />
</a>
{%- elsif {{include.material}} %}
<a
  class="no_icon nohover"
  data-toggle="tooltip"
  title="TeSS Material: {{include.material}}"
  href="https://tess.elixir-europe.org/materials/{{include.material}}" >
  Topic related training:
  <img
    style="background-color: #f47d20"
    class="registry_logo"
    src="images/tess_logo.svg"
    alt="TeSS logo" />
</a>
{%- endif %}
```

I can pull your changes into my branch :)

**Comment by christopherchild** [comment]
I have reverted the changes and this PR is now ready to be merged. I don't have permissions to do it myself.

**Comment by bedroesb** [comment]
Thank you for your patience!

**Pull request merged**
