### PR TITLE
2 tags filtering support + only H2 in toc

### LINKED ISSUE #140: Biomolecular Simulation Data
**What topic do you wish to add?**
New Domain related to Biomolecular Simulation Data.

**Are there existing pages in the RDM toolkit website related to the requested page?**
No

**Resources**
If there are there resources that could be utilised for writing the new page, please list them below:
N/A

**Context**
If this request is coming from a particular project, domain, or use-case please list them below:
WP5 use case about Biomolecular Simulation Data

### LINKED ISSUE #141: IDP use case
**What topic do you wish to add?**
Please provide a brief description.

IDP use case "Your domain" page. It would deal with IDP user community related processes

**Are there existing pages in the RDM toolkit website related to the requested page?**
No

**Resources**
If there are there resources that could be utilised for writing the new page, please list them below:

**Context**
If this request is coming from a particular project, domain, or use-case please list them below:
IDP user community

### PR DESCRIPTION
**Pull request by bedroesb**
- [x] new domains links in sidepanel, will close #141 and close #140 
- [x] tool resource lists can now be filtered with 2 tags by using the tag2 attribute:
  ```
  {% include toollist.html tag="human data" tag2="share"%}
  ```
- [x] Table of contents only shows H2 titles

### CODE REVIEW

**Comment by bedroesb** [comment]
@martin-nc you are automatically assigned to this PR because I made you CODEOWNER of the css directory. We can change this off course... I changed in this PR that the 'base' styling of the TOC is linked to a class and not the ID, because otherwhise if a page has no / or not enough titles, it will do the styling on the empty div like seen here: https://rdm.elixir-europe.org/assembly_example.html . I also changed that if there is only one subtitle, the TOC should not be shown

**Comment by martin-nc** [comment]
@bedroesb Ah, okay. Are we likely to get an empty div at the top? If so, perhaps the `:empty` selector could target it and hide it? Otherwise, looks fine to me. Shall I merge it or do you want others to review first?

**Comment by bedroesb** [comment]
by default (so if toc=false is not in the frontmatter) <div id="toc"></div> will be inserted. This div will be empty if the number of H2 headers is less than 2. But I could indeed  work with the empty selector! let e give it a try

**Comment by bedroesb** [comment]
@martin-nc I added display="none" when it is number of headers < than minimum

**Review by martin-nc — APPROVED** [review]
Looks fine now.

**Pull request merged**
