### PR TITLE
Adding FAIRsharing links for the resources listed

### PR DESCRIPTION
**Pull request by Drosophilic**
Please let me know if this type of contribution is appropriate. Happy to help where I can.

### CODE REVIEW

**Comment by bedroesb** [comment]
@Drosophilic thank you for your contribution! as you can read [here](https://rdm.elixir-europe.org/tool_resource_update.html) the yaml file is automatically build on the csv file. So please make changes against the the csv file because otherwhise your changes will be overwritten by the bot.

**Comment by Drosophilic** [comment]
Oops! Sorry, I didn't see that.

**Comment by bedroesb** [comment]
@Drosophilic sorry for that, it was ade this way so people would be able to open the csv in excel and have an easy overview of the potential long list of tool/resources

**Comment by Drosophilic** [comment]
No worries. I'll make the changes in the CSV.

**Pull request closed without merging**
